#!/bin/sh

userresources="${XDG_CONFIG_HOME:-$HOME/.config}"/X11/Xresources
usermodmap="${XDG_CONFIG_HOME:-$HOME/.config}"/X11/Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

[ -f "$userresources" ] && xrdb -merge "$userresources"
[ -f "$usermodmap" ] && xmodmap "$usermodmap"
[ -f "$sysresources" ] && xrdb -merge "$sysresources"
[ -f "$sysmodmap" ] && xmodmap "$sysmodmap"

xset b off &
xset r rate 300 50 &

userwallpaper="${XDG_DATA_HOME:-$HOME/.local/share}"/wallpaper
[ -f "$userwallpaper" ] && xwallpaper --zoom "$userwallpaper" &

# autostart
pidof -q mpd || mpd &
xbanish -t 5 -m ne &
dunst &
redshift &
xsidle slock setxkbmap us &
statusbar &

# wm/de
exec dwm 2> /tmp/dwm.log
