#!/bin/sh

for i in /etc/X11/Xresources/* "${XDG_CONFIG_HOME:-~/.config}"/X11/Xresources;
do
	[ -f "$i" ] && xrdb -merge "$i"
done
xset b off
xset r rate 300 50

# autostart
pidof -q mpd || mpd &
xbanish -t 5 &
dunst &
xsidle slock setxkbmap us &
gammastep &
statusbar &
[ -f "${XDG_DATA_HOME:-~/.local/share}"/wallpaper ] \
	&& xwallpaper --zoom "${XDG_DATA_HOME:-~/.local/share}"/wallpaper

# wm/de
exec dwm 2> /tmp/dwm.log
