#!/bin/sh

userresources="$XDG_CONFIG_HOME"/X11/Xresources
usermodmap="$XDG_CONFIG_HOME"/X11/xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

[ -f "$userresources" ] && xrdb -merge "$userresources"
[ -f "$usermodmap" ] && xmodmap "$usermodmap"
[ -f "$sysresources" ] && xrdb -merge "$sysresources"
[ -f "$sysmodmap" ] && xmodmap "$sysmodmap"

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
	for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
		[ -x "$f" ] && . "$f"
	done
	unset f
fi

xset b off &
xset r rate 300 50 &
#xsetroot -solid '#333333' &

#userwallpaper="${XDG_DATA_HOME:-$HOME/.local/share}"/wallpaper
#[ -f "$userwallpaper" ] && hsetroot -fill "$userwallpaper" &

# autostart
sxhkd -r /tmp/sxhkd.log &
pidof mpd || mpd &
xbanish -t 5 -m ne &
redshift &
xsidle.sh slock &
statusbar &
#stalonetray -c "$XDG_CONFIG_HOME"/stalonetray/stalonetrayrc &
#nm-applet &

# wm/de
#exec i3
exec dwm 2> /tmp/dwm.log
