#!/bin/sh

xset b off
xset r rate 300 50
[ -f ~/.config/X11/Xresources ] && xrdb -merge ~/.config/X11/Xresources
[ -f ~/.local/share/wallpaper.conf ] && setbg >/dev/null

# Need to be forked in the background.
xbanish -t 5 &
gammastep &
statusbar &
#qbittorrent &

# Launch WM/DE.
exec dwm
#exec wmaker
