#!/bin/sh

userresources="$XDG_CONFIG_HOME/X11/Xresources"
usermodmap="$XDG_CONFIG_HOME/X11/xmodmap"
userwallpaper="$XDG_DATA_HOME/wallpaper"

[ -f "$userresources" ] && xrdb -load "$userresources"
[ -f "$usermodmap" ] && xmodmap "$usermodmap"
[ -f "$userwallpaper" ] && xwallpaper --zoom "$userwallpaper"

# start some nice programs
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
	for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
		[ -x "$f" ] && . "$f"
	done
	unset f
fi

[ -f "$XDG_CONFIG_HOME/X11/xprofile" ] && . "$XDG_CONFIG_HOME/X11/xprofile"

# wm/de
exec dwm 2> ~/.dwm.log
