#!/bin/sh

userresources="$XDG_CONFIG_HOME/X11/xresources"
usermodmap="$XDG_CONFIG_HOME/X11/xmodmap"
userwallpaper="$XDG_DATA_HOME/wallpaper"

# X configuration
[ -f "$userresources" ] && xrdb -load "$userresources"
[ -f "$usermodmap" ] && xmodmap "$usermodmap"
[ -f "$userwallpaper" ] && xwallpaper --zoom "$userwallpaper"
xset b off &
xset r rate 300 50 &

# keybindings
sxhkd &

# music
[ ! -s "$XDG_CONFIG_HOME/mpd/pid" ] && mpd &

# notifications
dunst &

# hide cursor when inactive
xbanish -t 5 -m ne &

# screen color temprature
redshift &

# systray
stalonetray &

# networking
nm-applet &

# statusbar
slstatus &

# wm/de
exec dwm &> "$HOME/dwm.log"
