#!/bin/sh

case "$1" in
	"C-x")
		xclip -in -filter | tr '\n' ' ' | xclip -in -selection clipboard
		;;
	"C-c")
		while read file
		do
			xclip -selection clipboard -target image/png "$file"
		done
		;;
	"C-g")
		tr '\n' '\0' | xargs -0 gimp &
		;;
	"C-r")
		while read file
		do
			rawtherapee "$file" &
		done
		;;
esac
