#!/bin/sh

exec 2>/dev/null

filename="${1##*/}"

if [ -n "$4" ]; then # image mode
	printf "%s" "nsxiv - ${filename} | ${4}x${5} ${6}% [${2}/${3}]"
else
	printf "%s" "nsxiv - ${filename} [${2}/${3}]"
fi
