#!/bin/sh
#
# Backs up important files on my system.

files="$HOME/.local/share/bookmarks.csv $HOME/Pictures/Redmi $HOME/Documents/LaTeX"

for prev_tar in "$HOME"/Other/bkp_*.tar.gz;
do
	/bin/rm -- "$prev_tar"
done

fname=$(/bin/date +'%F_%H-%M-%S')
/bin/tar -czf ~/bkp_"$fname".tar.gz $files
