#!/bin/sh

# TODO: add missing dmenu prompts
# TODO: exit codes are a mess

bmks="$HOME"/bookmarks.csv
[ -f "$bmks" ] || exit 1

query_bookmarks() {
	len=$(wc -l "$bmks")
	sel=$(awk -F ',' 'NR>1 {print $1}' "$bmks" \
		| sort \
		| dmenu -i -l "$len")
	[ -z "$sel" ] && return

	grep "$sel" "$bmks"  # returns entire row (title,url)
}

get_bookmark_url() {
	row=$(query_bookmarks)
	[ $? ] || return  # empty input
	[ -z "$row" ] && return 1  # grep unsuccessful

	url="${row#*,}"
	[ -z "$url" ] && return 1  # title exists, but no url (aka, you're dumb)
	printf '%s' "$url"
}

new_bookmark() {
	title=$(dmenu -p 'Title:' < /dev/null)
	[ -z "$title" ] && return  # empty input

	url=$(dmenu -p 'Link:' < /dev/null)
	[ -z "$url" ] && return 1  # provided title, but not url

	printf '%s,%s' "$title" "$url"
}

del_bookmark() {
	bookmark=$(query_bookmarks)
	grep -v "$bookmark" "$bmks"
}

# TODO: show a notification after each action
action=$(printf 'open\ncopy\ninsert\ndelete' | dmenu -i)
case $action in
	open)
		"$BROWSER" "$(get_bookmark_url)" 2>/dev/null
		;;
	copy)
		get_bookmark_url | xclip -i -selection clipboard
		;;
	insert)
		new_bookmark >> "$bmks"
		;;
	delete)
		del_bookmark >> "$bmks.$$"
		mv "$bmks.$$" "$bmks"
		;;
	*)
		;;
esac
