#!/usr/bin/env bash

mounted=$(lsblk -lp | awk '$7 ~ /media/ {print $1, "("$4")"}')
[ "$mounted" ] || exit 1

prompt='Unmount which device?'
device=$(echo "$mounted" | dmenu -i -p "$prompt" | awk '{print $1}')
[ "$device" ] || exit

sudo umount "$device" && notify-send 'Unmounted removable device' "$device"
