#!/bin/sh
#
# Helper script for adding dwm(1) rules.
#
# See also:
# 	lsw(1) <https://git.suckless.org/lsw>
# 	dmenu(1)
# 	cut(1)
# 	xargs(1)
# 	xprop(1)

xwindow_info() {
	sel=$(lsw | dmenu -l 10 -i)
	if [ -n "$sel" ]; then
		case $1 in
			WM_NAME|WM_CLASS)
				echo "$sel" | cut -d ' ' -f 1 | xargs xprop -id | grep "$1"
				return $?
				;;
			*)
			  ;;
		esac
	fi
	return 1
}

case $1 in
	-h)
		printf "usage: dmenu_wmclass [-n|-t]\n" >&2
		exit 0
		;;
	-n|-t)
		xwindow_info 'WM_NAME'
		;;
	'')
		xwindow_info 'WM_CLASS'
		;;
	*)
		printf "usage: dmenu_wmclass [-n|-t]\n" >&2
		exit 1
		;;
esac
