#!/bin/sh
#
# Helper script for adding dwm(1) rules.

set -e

xwindow_info() {
	# for lsw, see https://git.suckless.org/lsw
	lsw | dmenu -l 10 -i | awk '{print $1}' | xargs xprop -id
	return $?
}

print_usage() {
	printf "usage: %s [-n|-t]\n" "$(basename "$0")" >&2
	return $1
}

case $1 in
	-h)
		print_usage 0
		;;
	-n|-t)
		xwindow_info | grep 'WM_NAME'
		;;
	'')
		xwindow_info | grep 'WM_CLASS'
		;;
	*)
		print_usage 1
		;;
esac
exit $?
