#!/bin/sh

_name=$(basename "$0")
_time=$(dmenu -p 'Time (defaults to seconds):' < /dev/null)
_desc=$(dmenu -p 'Add a description:' < /dev/null)

if [ ! -z "$_time" ];
then
	_time_full=$(printf '%s' "$_time" | tr -d '[:space:]')
	notify-send "$_name" "Set a timer for $_time_full"
	sleep "$_time_full"
	notify-send -u critical "$_name" \
		"${_desc:-"Your $_time_full timer has ended"}"
fi
