#!/bin/sh
#
# Run the 'aueb-to-date' script to get the latest semester schedule and replace
# it with the existing one, if there have been changes.

month=$(date +%m)
year=$(date +%y)
if [ "$month" -gt 2 ] && [ "$month" -le 9 ]; then
	myfile="$HOME/Documents/AUEB/spring$((year - 1))-$((year)).pdf"
elif [ "$month" -le 2 ]; then
	myfile="$HOME/Documents/AUEB/winter$((year - 1))-$((year)).pdf"
else
	myfile="$HOME/Documents/AUEB/winter$((year))-$((year + 1)).pdf"
fi
printf "month = %s, year = %s\nfilename = %s" "$month" "$year" "$myfile"

tmpfile=$(mktemp)

# If download failed, bail out.
"$HOME"/.local/bin/aueb-to-date "$tmpfile"
status=$?
if [ "$status" -ne 0 ]; then
	/usr/bin/rm -v -- "$tmpfile"
	exit "$status"
fi

if /usr/bin/cmp -- "$tmpfile" "$myfile"; then
	echo 'The schedule has not been updated.'
else
	echo 'The schedule has been updated.'

        # For POSIX compliance...
	if command -v install >/dev/null 2>&1; then
		/usr/bin/install -v -m 644 -- "$tmpfile" "$myfile"
	else
		/usr/bin/cp -v -- "$tmpfile" "$myfile"
		/usr/bin/chmod -- 644 "$myfile"
	fi
fi
/usr/bin/rm -v -- "$tmpfile"

exit $?
