#!/bin/sh

depth=1

case $1 in
	"$HOME"/Documents/AUEB)
		depth=4
		;;
	"$HOME"/Programming)
		depth=2
		;;
esac

cd "$1" || exit 1
target=$(find . -maxdepth "$depth" -type d | fzf --prompt 'Which directory? ')

if [ "$target" ]; then
	cd "$target" || exit
else
	cd - > /dev/null 2>&1 || exit
fi
