#!/bin/sh

sel=$(find "$HOME"/Documents/Markdown -name '*.md' | fzf)
[ -z "$sel" ] && exit

if [ "$1" = '-p' ]; then
	if command -v lowdown >/dev/null 2>&1; then
		exec lowdown -tterm "$sel" | "${PAGER:-less}" -R
	else
		exec "${PAGER:-less}" "$sel"
	fi
else
	exec "${VISUAL:-vim}" "$sel"
fi
