#!/bin/sh

open_here() {
	if [ "$(whereis $1 >/dev/null 2>&1)" ]; then
		printf "md: install $1 first\n"
		exit 1
	else
		"$1" .
	fi
}

md_dir="$HOME"/Documents/Markdown
cd "$md_dir" || exit 1
printf "1) $VISUAL\n2) ranger\n3) cutemarked\nChoose an application: "
read -r REPLY
printf "\n"
case $REPLY in
	1|v*)
		open_here "${VISUAL:-vim}"
		;;
	2|r*)
		open_here ranger
		;;
	3|c*)
		open_here cutemarked
		;;
	*)
		printf "md: invalid option\n" 2>&1
		exit 2
		;;
esac
