#!/bin/sh

open_here() {
	if [ "$(which $1 2>/dev/null)" ]; then
		"$1" .
	else
		printf 'md: install %s first\n' "$1" 1>&2
		return 1
	fi
}

md_dir="$HOME"/Documents/Markdown
cd "$md_dir" || exit 1
printf '1) %s\n2) ranger\n3) cutemarked\nChoose an application: ' "$VISUAL"
read -r REPLY
case $REPLY in
	1|v*)
		open_here "${VISUAL:-vim}"
		;;
	2|r*)
		open_here ranger
		;;
	3|c*)
		open_here cutemarked
		;;
	*)
		printf 'md: invalid option\n' 1>&2
		exit 2
		;;
esac
