#!/bin/sh

show_usage() {
	printf  "usage:\n\tmonconn [0|1]\n" >&2
}

if [ $# != 1 ];
then
	show_usage
	exit 1
fi

case $1 in
	0)
		xrandr --output HDMI-1 --mode 1920x1080 \
			&& xrandr --output eDP-1 --off \
			&& xset r rate 300 50
		;;
	1)
		xrandr --output eDP-1 --mode 1920x1080 \
			&& xrandr --output HDMI-1 --off \
			&& xset r rate 300 50
		;;
	*)
		show_usage
		exit 1
		;;
esac
