#!/bin/sh

walldir="${1:-"$HOME/Pictures/Wallpapers"}"
cd "$walldir" || exit 2

len=$(find . -maxdepth 1 -type f -printf x | wc -c)
prompt="Select or type 'none'"
image=$(file -- * | awk -F ':' '/image/ {print $1}' \
	| dmenu -i -p "$prompt" -l "$len")

wallpaper="${XDG_DATA_HOME:-$HOME/.local/share}"/wallpaper
case $image in
	'')
		;;
	none)
		xwallpaper --clear && rm -f "$wallpaper"
		;;
	*)
		xwallpaper --zoom "$image" && ln -sf "$PWD/$image" "$wallpaper"
		;;
esac
