#!/bin/sh

walldir="${1:-"$HOME/Pictures/Wallpapers"}"
cd "$walldir" || exit 2

prompt="Image or 'none':"
len=$(find -type f -printf x | wc -c)
[ "$len" -gt 50 ] && len=50
image=$(find -type f | sed 's/^\.\///' | dmenu -i -p "$prompt" -l "$len")

wallpaper="${XDG_DATA_HOME:-$HOME/.local/share}"/wallpaper
case $image in
	'')
		;;
	none)
		xwallpaper --clear && rm -f "$wallpaper"
		;;
	*)
		xwallpaper --zoom "$image" && ln -sf "$PWD/$image" "$wallpaper"
		;;
esac
