#!/bin/sh

walldir="${1:-"$HOME/Pictures/Wallpapers"}"
cd "$walldir" || exit 2

length=$(ls | wc -l)
prompt="Select one or type 'none'"
image=$(file -- * | awk --field-separator=: '/image/ {print $1}' \
	| dmenu -i -p "$prompt" -l "$length")

wallpaper="${XDG_DATA_HOME:-$HOME/.local/share}"/wallpaper
case $image in
	'')
		exit
		;;
	none)
		hsetroot -clear && rm -f "$wallpaper"
		;;
	
	*)
		hsetroot -fill "$image" && ln -sf "$PWD/$image" "$wallpaper"
		;;
esac
