#!/bin/sh
#
# TODO Description
#
# See:
#   basename(1)
#   head(1)
#   tail(1)
#   xwallpaper(1)

set -eu

show_usage() {
	prog_name=$(basename "$0")
	printf 'usage: %s [-h|--help] [-m|--mode <mode>] [target_img]\n' \
		"$prog_name" >&2
}

check_mode() {
	case $1 in
		center|focus|maximize|stretch|tile|zoom)
			# xwallpaper has other options too, these are the ones I care about
			return 0
			;;
		*)
			printf "Bad mode: '%s'\nSee OPTIONS in xwallpaper(1).\n" "$1" >&2
			return 2
			;;
	esac
}

bad_img() {
	printf "Bad target image: '%s'.\n" "$1" >&2
}

# Accept 4 arguments maximum; don't bother otherwise
if [ "$#" -gt 4 ]; then
	show_usage
	exit 1
fi

# TODO Check dependencies

while [ "$#" -gt 0 ]; do
	case $1 in
		-h|--help)
			show_usage
			exit 1
			;;

		-m|--mode)
			# If we see -m, that means the next argument should be the mode
			mode=$2
			if check_mode "$mode"; then
				shift
			else
				status=$?
				show_usage
				exit "$status"
			fi
			;;

		*)
			# Any other argument should be considered the target image
			target_img=$1
			;;
	esac
	shift
done

# If no arguments were given, get the defaults from ~/.local/share/wallpaper.conf
target_img=${target_img:-NONE}
[ "$target_img" = NONE ] && target_img=$(head -n 1 ~/.local/share/wallpaper.conf)
mode=${mode:-NONE}
[ "$mode" = NONE ] && mode=$(tail -n 1 ~/.local/share/wallpaper.conf)

# Sanity check image file
if [ ! -f "$target_img" ]; then
	show_usage
	bad_img "$target_img"
	exit $?
fi

printf 'cmd: xwallpaper --%s %s\n' "$mode" "$target_img" >&2
xwallpaper "--$mode" "$target_img"
