#!/bin/sh
#
# Simple statusbar for dwm(1).  Use it in your ~/.xinitrc (or $XINITRC).

volume() {
	if command -v pamixer >/dev/null 2>&1;
	then
		vol=$(pamixer --get-volume-human)
		sink=$(pamixer --get-default-sink \
			| awk -F'" "' 'NR == 2 {print $2}' | tr '"' ':')
		printf '%s %s' "$sink" "$vol"
	else
		printf 'n/a'
	fi
} 

battery() {
	case $(cat /sys/class/power_supply/BAT?/status) in
		Discharging)
			symbol='-'
			;;
		Charging)
			symbol='+'
			;;
		*)
			symbol='='
			;;
	esac
	printf '%s%%%s' "$(cat /sys/class/power_supply/BAT?/capacity)" "$symbol"
}

kb() {
	setxkbmap -query | awk '$1 == "layout:" {print $2}'
}

ipv4() {
	iproute=$(ip -4 -br route)
	if [ -z "$iproute" ];
	then
		printf 'n/a'
		return $?
	fi
	ifandip=$(echo $iproute | awk '/default/ {print $5": "$9}')
	ssid=$(nmcli con show --active | awk -F'  ' 'NR == 2 {print $1}')  # FIXME
	if [ -z "$ssid" ];
	then
		printf "%s" "$ifandip"
	else
		printf "%s (%s)" "$ifandip" "$ssid"
	fi
}

memory() {
	free -h | awk 'NR == 2 {print $3"/"$2}'
}

while xsetroot -name " $(ipv4) | $(volume) | M: $(memory) | B: $(battery) | $(date)"
do
	sleep 5
done
