#!/bin/sh

volume() {
	# automatically starts the pulseaudio daemon as well
	pamixer --get-volume-human
}

battery() {
	case $(cat /sys/class/power_supply/BAT?/status) in
		Discharging)
			symbol='-'
			;;
		Charging)
			symbol='+'
			;;
		*)
			symbol='='
			;;
	esac
	printf '%s%%%s' "$(cat /sys/class/power_supply/BAT?/capacity)" "$symbol"
}

kb() {
	setxkbmap -query | awk '$1 == "layout:" {print $2}'
}

ipv4() {
	# TODO: don't hardcode the interface name here
	address=$(ip -4 -br a | awk '/wlp1s0/ {print $3}')
	if [ -n "$address" ];
	then
		ssid=$(nmcli connection show --active | awk '/wlp1s0/ {print $1}')
		printf '%s: %s' "$ssid" "$address"
	else
		printf 'n/a'
	fi
}

memory() {
	free -h | awk 'NR == 2 {print $3}'
}

while xsetroot -name " $(ipv4) | V: $(volume) | M: $(memory) | B: $(battery) | K: $(kb) | $(date)"
do
	sleep 5
done
