#!/bin/sh

volume() {
	# automatically starts the pulseaudio daemon as well
	pamixer --get-volume-human
}

battery() {
	case $(cat /sys/class/power_supply/BAT?/status) in
		Discharging)
			symbol='-'
			;;
		Charging)
			symbol='+'
			;;
		*)
			symbol='='
			;;
	esac
	printf '%s%%(%s)' "$(cat /sys/class/power_supply/BAT?/capacity)" "$symbol"
}

kb() {
	setxkbmap -query | awk '$1 == "layout:" {print $2}'
}

ipv4() {
	address=$(ip addr | awk '/inet/ && /wlp1s0/ {print $2}')
	if [ "$address" ];
	then
		printf '%s' "$address"
	else
		printf 'n/a'
	fi
}

memory() {
	free -h | awk '/^Mem:/ {print $3}'
}

while xsetroot -name " `ipv4`  `volume`  `memory`  `battery`  `kb`  `date`"
do
	sleep 5
done
