#!/bin/sh

gtksettings="${XDG_CONFIG_HOME:-"$HOME/.config"}"/gtk-3.0/settings.ini
[ -f "$gtksettings" ] || exit 1
yesdark='prefer-dark-theme=1'
nodark='prefer-dark-theme=0'
hours=$(date +'%H')

if [ "$hours" -gt 7 ] && [ "$hours" -lt 19 ]; then
	sed -i "s/$yesdark/$nodark/" "$gtksettings"
else
	sed -i "s/$nodark/$yesdark/" "$gtksettings"
fi
