" ~/.vim/vimrc
"
" Author: Peter Frangatzis
" Date: Tue Jul 30 2024

" Most distros turn compatible off by default through a global vimrc.
"set nocompatible

" Vi-compatible options (~/.exrc). {{{
set autoindent
set ignorecase
"set number
set showmatch
set showmode
" }}}

" Do not clutter directories with vim-specific junk. {{{
set backup
set backupdir=~/.cache/vim/backup
if has('persistent_undo')
	set undofile
	set undodir=~/.cache/vim/undo
endif
set directory-=.
" }}}

" Colors & syntax highlighting. {{{
if has('syntax')
	set hlsearch
	set colorcolumn=+1

	" Customize colorschemes
	let g:zenburn_alternate_Visual=0
	let g:nofrils_strbackgrounds=1
	let g:nofrils_heavycomments=1
	let g:nofrils_heavylinenumbers=0

	" Set the colorscheme, unless we're in a tty
	"if &term !~# 'linux'
	"	if &background ==# 'light'
	"		colorscheme nofrils-acme
	"	else
	"		colorscheme nofrils-dark
	"	endif
	"endif
endif
" }}}

" GUI options. {{{
if has('gui_running')
	" Kill gui popup dialogs.
	set guioptions+=c
endif
" }}}

" General options. {{{
set cursorline
set cursorlineopt=number
set display=truncate                 " show @@@ if last line truncated
set hidden                           " allow switching between unwritten buffers
set incsearch
"set laststatus=2                     " always show the bottom statusbar
set lazyredraw                       " do not redraw when executing macros
set listchars=tab:»\ ,trail:-,eol:¬
set nofoldenable                     " start with folds disabled
set path+=**                         " the 'find' command searches recursively
set shiftround
set showcmd                          " display incomplete commands
set smartcase
set smartindent
set spelllang=en,el
set statusline=%<%f\ %h%m%r
set statusline+=[%{&ff}]\ 
set statusline+=%{FugitiveStatusline()}
set statusline+=%=%k\ [%B]\ %-14.(%l,%c%V%)\ %P
set suffixes+=.class
set textwidth=80
set ttimeout
set ttimeoutlen=100
set visualbell
if has('wildmenu')
	set wildmenu
	set wildignorecase
endif
" }}}

" (Re)mappings. {{{
nnoremap <Leader><Leader> :set keymap=greek_utf-8<CR>
nnoremap <silent> <C-l> :nohl<CR>
nnoremap <silent> <Leader>gs :G<CR>
nnoremap <silent> <Leader>ls :set list!<CR>
nnoremap <silent> <Leader>sp :set spell!<CR>
nnoremap <silent> <Leader>n :set number!<CR>
:command W w
:command Q q
" }}}

" Global variables. {{{
let c_curly_error=1
let c_function_pointers=1
let c_functions=1
let c_minlines=20
let c_no_comment_fold=1
let c_space_errors=1
let c_syntax_for_h=1
let g:html_syntax_folding=1
let g:markdown_folding=1
let g:markdown_minlines=500
let g:netrw_banner=0
let g:nroff_is_groff=1
let g:nroff_space_errors=1
let g:preprocs_as_sections=1
let g:xml_syntax_folding=1
let java_highlight_java_io=1
let java_highlight_java_lang_ids=1
let java_mark_braces_in_parens_as_errors=1
let java_minlines=50
" }}}

" Autocommands. {{{
autocmd BufWritePost *Xresources,*Xdefaults :!xrdb -merge %
autocmd BufNewFile,BufRead ~/Documents/Notes/* :setlocal spell keymap=greek_utf-8
autocmd BufNewFile,BufRead *todo.txt :setlocal textwidth&
autocmd BufWritePre *todo.txt :%!sort
" }}}

" Enable filetype detection and loading of filetype-specific plugins.
filetype plugin indent on

" Make the '%' command work for more stuff (for example, HTML tags).
if has('syntax') && has('eval')
	packadd! matchit
endif

" Debian turns modeline off by default. I don't disagree with this choice,
" I just like living dangerously. ;)
set modeline

" Disable matchparen plugin, because the highlighting confuses me.
let loaded_matchparen=1

" vim: fdm=marker ts=2 sts=2 sw=2
