" ~/.vim/vimrc
"
" Author: Peter Frangatzis
" Date: Tue Jul 30 2024

" Most distros turn compatible off by default through a global vimrc.
"set nocompatible

" Vi-compatible options (~/.exrc). {{{
set autoindent
set ignorecase
"set number
set showmatch
set showmode
" }}}

" Do not clutter directories with vim-specific junk. {{{
set backup
set backupdir=~/.cache/vim/backup
if has('persistent_undo')
	set undofile
	set undodir=~/.cache/vim/undo
endif
set directory-=.
" }}}

" Color terminal/GUI options. {{{
if &t_Co > 2 || has("gui_running")
	if has("syntax")
		syntax enable
	endif
	set hlsearch
	set colorcolumn=+1

	" Kill gui popup dialogs.
	set guioptions+=c

	function! ToggleBG()
		if &background ==# 'light'
			set background=dark
		else
			set background=light
		endif
	endfunction

	" Set the colorscheme.
	let g:zenburn_alternate_Visual=1
	let g:zenburn_high_Contrast=1
	colorscheme zenburn

	" Make terminal background transparent (optional).
	"hi Normal ctermbg=NONE
endif
" }}}

" General options. {{{
set display=truncate                 " show @@@ if last line truncated
set hidden                           " allow switching between unwritten buffers
set incsearch
set lazyredraw                       " do not redraw when executing macros
set listchars=tab:»\ ,trail:-,eol:¬
set nofoldenable                     " start with folds disabled
set path+=**                         " the "find" command searches recursively
set showcmd                          " display incomplete commands
set smartcase
set smartindent
set statusline=%<%f\ %h%m%r
set statusline+=%{FugitiveStatusline()}
set statusline+=%=%k\ %-14.(%l,%c%V%)\ %P
set suffixes+=.class
set textwidth=80
set ttimeout
set ttimeoutlen=100
if has("wildmenu")
	set wildmenu
	set wildignorecase
endif
" }}}

" (Re)mappings. {{{
map <silent> <F6> :call ToggleBG()<CR>
nnoremap <Leader><Leader> :set keymap=greek_utf-8<CR>
nnoremap <silent> <C-l> :nohl<CR>
nnoremap <silent> <Leader>gs :G<CR>
nnoremap <silent> <Leader>ls :set list!<CR>
nnoremap <silent> <Leader>sp :set spell!<CR>
nnoremap <silent> <Leader>n :set number!<CR>
:command W w
:command Q q
" }}}

" Global variables. {{{
let c_comment_strings=1
let c_curly_error=1
let c_minlines=20
let c_no_comment_fold=1
let c_syntax_for_h=1
let g:html_syntax_folding=1
let g:markdown_folding=1
let g:markdown_minlines=500
let g:netrw_banner=0
let g:nroff_is_groff=1
let g:nroff_space_errors=1
let g:preprocs_as_sections=1
let g:xml_syntax_folding=1
let java_highlight_java_io=1
let java_highlight_java_lang_ids=1
let java_mark_braces_in_parens_as_errors=1
let java_minlines=50
" }}}

" Autocommands. {{{
autocmd BufWritePost *Xresources,*Xdefaults :!xrdb -merge %
" }}}

" Enable filetype detection and loading of filetype-specific plugins.
filetype plugin indent on

" Make the "%" command work for more stuff (for example, HTML tags).
if has('syntax') && has('eval')
	packadd! matchit
endif

" Debian turns modeline off by default. I don't disagree with this choice,
" I just like living dangerously. ;)
set modeline

" vim: fdm=marker ts=2 sts=2 sw=2
