#!/bin/sh
#
# Uses dmenu and xwallpaper.

# If no directory was provided, look in the one I use on my system.
walldir="$HOME/Pictures/Wallpapers"
[ "$1" == "" ] || walldir="$1"
[ ! -d "$walldir" ] && exit -1

# List out all images and choose one.
cd "$walldir"
wallpaper=$(find *.jpg *.png *.jpeg | dmenu -l 30 -p "Select a wallpaper:")
[ "$wallpaper" == "" ] && exit

# Set the selected image as the wallpaper and create a symlink to it.
xwallpaper --zoom "$wallpaper"
ln -sf -- "$PWD/$wallpaper" "$XDG_DATA_HOME/wallpaper"
