#!/bin/sh

walldir="${1:-"$HOME/Pictures/Wallpapers"}"
cd "$walldir" || exit 2

length=$(ls | wc -l)
prompt='Select an image:'
image=$(file -- * | awk --field-separator=: '/image/ {print $1}' \
	| dmenu -i -p "$prompt" -l "$length")

# symlink selected image to default wallpaper location
wallpaper="$XDG_DATA_HOME"/wallpaper
case $image in
	'')
		exit
		;;
	none)
		hsetroot -clear && ln -sf none "$wallpaper"
		;;
	*)
		hsetroot -fill "$image" && ln -sf "$PWD/$image" "$wallpaper"
		;;
esac
