#!/bin/sh
#
# Setting wallpapers the minimalist way.
# Uses pywal when USE_PYWAL=1. (duh)
# NOTE: Background this script when passing a directory as an argument.

# TODO make this a command line option
USE_PYWAL=0

if [ -f "$1" ]; then
    xwallpaper --zoom "$1" && cp -f "$1" "$XDG_DATA_HOME/wallpaper"
    if [ $USE_PYWAL -eq 1 ]; then
        [ -f /usr/bin/wal ] && wal -i "$1" -q
        [ -f /usr/bin/pywalfox ] && pywalfox update
        genzathurarc > "$XDG_CONFIG_HOME/zathura/pywaltheme"
        xrdb -load "$XDG_CONFIG_HOME/X11/xresources"
    fi
elif [ -d "$1" ]; then
    while true; do
        WALLPAPER=$(ls "$1"/*.png "$1"/*.jpg | shuf -n 1)
        xwallpaper --zoom "$WALLPAPER" && cp -f "$WALLPAPER" "$XDG_DATA_HOME/wallpaper"
        if [ $USE_PYWAL -eq 1]; then
            [ -f /usr/bin/wal ] && wal -i "$1/$WALLPAPER" -q
            [ -f /usr/bin/pywalfox ] && pywalfox update
            genzathurarc > "$XDG_CONFIG_HOME/zathura/pywaltheme"
            xrdb -load "$XDG_CONFIG_HOME/X11/xresources"
        fi
        sleep 30m
    done
else
    echo "Invalid target. Please provide either an image or a directory."
    exit
fi
