#!/bin/sh
#
# Show info of current song played by mpd in a notification.
# Also creates thumbnails of album covers.

music_dir="$HOME/music"
preview_dir="$XDG_CONFIG_HOME/ncmpcpp/previews"
filename="$(mpc --format "$music_dir"/%file% current)"
preview_name="$preview_dir/$(mpc --format %album% current | base64).png"

[ -e "$preview_name" ] || ffmpeg -y -i "$filename" -an -vf scale=128:128 \
    "$preview_name" > /dev/null 2>&1

TITLE="$(mpc --format '%title%' current)"
ARTIST="$(mpc --format '%artist%' current)"
ALBUM="$(mpc --format '%album%' current)"

notify-send "$TITLE" "<i>by </i>$ARTIST\n<i>from </i>$ALBUM" -i "$preview_name"
