#!/bin/sh

SRC_DIR="$HOME/.local/src"
[ ! -d "$SRC_DIR" ] && echo "$SCR_DIR does not exist." && exit 1

cd "$SRC_DIR"

PROGRAM_DIR="$(find . -maxdepth 2 -type d | fzf)"

if [ "$PROGRAM_DIR" = "" ]; then
	cd - 1> /dev/null
else
	cd "$SRC_DIR/$PROGRAM_DIR"
fi
