#!/usr/bin/env bash

SRC_DIR="$HOME/.local/src"
[[ ! -d "$SRC_DIR" ]] && echo "$SCR_DIR does not exist!!" && return

cd "$SRC_DIR"

PROGRAM_DIR="$(ls . | dmenu -p "For which program?")"
[[ "$PROGRAM_DIR" == "" ]] && return

cd "$SRC_DIR/$PROGRAM_DIR"
