#!/usr/bin/env bash
#
# Mount removable drives using dmenu.

MOUNTABLES=$(lsblk -lp | grep "part $" | awk '{print $1, "(" $4 ")"}')
[[ "$MOUNTABLES" = "" ]] && exit 1

DEVICE=$(echo "$MOUNTABLES" | \
	dmenu -i -p "Mount which drive?" | awk '{print $1}')
[[ "$DEVICE" = "" ]] && exit 1

which udisksctl && udisksctl mount --block-device "$DEVICE" && notify-send \
	-u low "Mounted removable drive" "$DEVICE @ /run/media/<i>$USER</i>"

# TODO use mount to do the job, in case udisksctl is not installed
